C++ Port
mike-lischke/antlr4-c3 pull request #83
Opened 2023-09-04 04:43 UTC by swillits

I grabbed the TypeScript and converted that directly to C++ so it's a very faithful translation of the original TypeScript. This'll make it easy to maintain and keep in-sync.

Two concerns:

1) In the antlr TS runtime, `RuleStartState` has a property `isPrecedenceRule` and in the C++ runtime there is not. Inspecting what the value of that property is though, it appears to me to be identical at all times to C++'s `isLeftRecursiveRule` so this code is currently just using that to get the right value. See lines 574 and 739. I'm not familiar enough with ANTLR's internals to understand what the indended difference is between those, so some guidance on that is needed.

2) It's working as expected in my testing, but I didn't spend time on understanding the TS unit tests and replicating those.

Lastly, I have made one addition which is also in this PR which is to add the ability for an external caller to cancel collecting candidates, and the collection to time itself out if it's taking too long. Both are opt-in and just short circuit to returning the incomplete candidate results. This is a pretty trivial addition in complexity (it's not aiming to be perfectly immediate), but useful in practice where the results are no longer needed (say because the user's input text has changed already and the results will therefore be stale).

2023-09-04 07:22 UTC, mike-lischke requested changes
Some tests would have been great, but I understand that setting them up is way more effort than the port itself, given how different platforms are.

Since I'm currently switching away from the contributors list to the Signed-off commit message, can you please add that to your patch (just run git with amend and the -s flag)? Thanks.

2023-09-04 15:54 UTC, swillits commented
Gotcha. Any idea about isPrecedenceRule vs isLeftRecursiveRule?

2023-09-05 08:44 UTC, mike-lischke commented
Yes, I think you are right. Use `isLeftRecursiveRule`.

2023-09-05 18:11 UTC, swillits commented
Thanks. Changes made and should be signed-off.

2023-09-06 08:05 UTC, mike-lischke approved these changes

2023-09-06 08:06 UTC, merged

2023-09-06 08:06 UTC, mike-lischke commented
great, thanks!